version: 0.2

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

      - WORKER_REPOSITORY_URI=${WORKER_REPOSITORY_URI}
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

      - COMMIT_HASH="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "COMMIT_HASH=${COMMIT_HASH}"
      - BUILD_NUM=${CODEBUILD_BUILD_NUMBER:-0}

      - IMAGE_TAG="${COMMIT_HASH}-${BUILD_NUM}"

      - echo "WORKER_REPOSITORY_URI=${WORKER_REPOSITORY_URI}"
      - echo "IMAGE_TAG=${IMAGE_TAG}"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker buildx create --use --name mybuilder
      - docker buildx inspect --bootstrap
      - |
          docker buildx build --provenance=false \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --build-arg BUNDLE_PATHS=${BUNDLE_PATH} \
            --cache-from type=registry,ref=$WORKER_REPOSITORY_URI:latest \
            --progress=plain \
            -t $WORKER_REPOSITORY_URI:latest \
            -t ${WORKER_REPOSITORY_URI}:${IMAGE_TAG} \
            -f Dockerfile \
            --output type=image,push=true .

  post_build:
    commands:
      - echo "Successfully finished build!!"
      - echo "Deploying worker..."
      - bash worker-deploy.sh
      - echo "Successfully finished deploying worker"
